###################################
#
# task start-all-local
#
###################################

# docker volume rm $(docker volume ls -q -f "dangling=true")

services:
  # ipfs:
  #   image: ipfs/kubo:v0.37.0
  #   container_name: ipfs
  #   network_mode: host
  #   ports:
  #     - "4001:4001"
  #     - "4001:4001/udp"
  #     - "8080:8080"
  #     - "5001:5001"
  #   stop_signal: SIGKILL
  #   command: daemon
  #   restart: unless-stopped

  ponder-db:
    image: postgres:17
    container_name: ponder-db
    environment:
      POSTGRES_DB: ponder
      POSTGRES_USER: ponder
      POSTGRES_PASSWORD: ponder
    volumes:
      - ponder-db-data:/var/lib/postgresql/data
    ports:
      - '6432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d ponder -U ponder']
      interval: 1s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  ponder:
    image: node:22-alpine
    container_name: ponder
    working_dir: /app/indexer
    network_mode: host
    volumes:
      - .:/app
    command: sh -c "npm install -g pnpm && CI=true pnpm install --ignore-scripts && pnpm run db:migrate && pnpm run start --schema v0.9.7 --views-schema trust-graph"
    depends_on:
      - ponder-db
    ports:
      - '65421:65421'
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'wget -q --spider http://localhost:65421/health || exit 1',
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://ponder:ponder@localhost:6432/ponder
    restart: unless-stopped

  ponder-server:
    image: node:22-alpine
    container_name: ponder-server
    working_dir: /app/indexer
    network_mode: host
    volumes:
      - .:/app
    command: sh -c "npm install -g pnpm && CI=true pnpm install --ignore-scripts && pnpm run serve --schema trust-graph"
    depends_on:
      ponder:
        condition: service_healthy
    ports:
      - '65422:65422'
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'wget -q --spider http://localhost:65422/health || exit 1',
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://ponder:ponder@localhost:6432/ponder
    restart: unless-stopped

volumes:
  ponder-db-data:
